### ISSUE TITLE
z-index issue on calendar

### ISSUE THREAD

**Issue by mahdi936** [Saeed-Khazaei/PersianDatePicker#2]
hello and thank you saeed for developing this beautiful component
there is a z-index issue on calendar box it has conflicts with mui components as you can see below image:

![image](https://user-images.githubusercontent.com/53161009/225558941-3c4fd6a2-9761-4214-aebd-987024b6823f.png)

**Comment by p-pey** [comment]
Hi @mahdi936 , its not a calendar issue you need to config your MUI or use inline styles in MUI components

**Comment by Saeed-Khazaei** [comment]
> Hi @mahdi936 , its not a calendar issue you need to config your MUI or use inline styles in MUI components

Thank you for your comment 👌
